DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (ID INT PRIMARY KEY, NAME VARCHAR(10));
INSERT INTO PERSON VALUES (1, 'Alice');
INSERT INTO PERSON VALUES (2, 'Bob');
INSERT INTO PERSON VALUES (3, 'Charlie');
