#!/bin/bash
# $Id: d2r-server,v 1.3 2006/09/18 12:01:33 cyganiak Exp $
if [ ! -e "./d2r-server" ]
then
  echo "Please cd into the D2R Server directory to run the server"
  exit 1
fi
D2RQ_ROOT=${0%/*}
SEP=':'
if [ "$(uname)" = "Cygwin" ]; then SEP=';'; fi
for jar in "$D2RQ_ROOT"/lib/*.jar "$D2RQ_ROOT"/lib/*/*.jar
do
  if [ ! -e "$jar" ]; then continue; fi
  if [ "$CP" != "" ]; then CP="$CP$SEP"; fi
  CP="$CP$jar"
done
LOGCONFIG=${LOGCONFIG:-file:$D2RQ_ROOT/etc/log4j.properties}
exec java -cp "$CP" "-Dlog4j.configuration=${LOGCONFIG}" d2r.server "$@"