#!/bin/bash
# $Id: generate-mapping,v 1.1 2006/09/07 16:57:50 cyganiak Exp $
if [ ! -e "./d2r-server" ]
then
  echo "Please cd into the D2R Server directory to run the server"
fi
D2RQ_ROOT=${0%/*}
SEP=':'
if [ "$(uname)" = "Cygwin" ]; then SEP=';'; fi
for jar in "$D2RQ_ROOT"/lib/*.jar "$D2RQ_ROOT"/lib/*/*.jar
do
  if [ ! -e "$jar" ]; then continue; fi
  if [ "$CP" != "" ]; then CP="$CP$SEP"; fi
  CP="$CP$jar"
done
LOGCONFIG=${LOGCONFIG:-file:$D2RQ_ROOT/etc/log4j.properties}
exec java -cp "$CP" "-Dlog4j.configuration=${LOGCONFIG}" d2r.server "$@"