#!/bin/bash
D2RQ_ROOT=${0%/*}
CP="$D2RQ_ROOT/build"
SEP=':'
if [ "$(uname)" = "Cygwin" ]; then SEP=';'; fi
for jar in "$D2RQ_ROOT"/lib/*.jar "$D2RQ_ROOT"/lib/*/*.jar
do
  if [ ! -e "$jar" ]; then continue; fi
  CP="$CP$SEP$jar"
done
LOGCONFIG=${LOGCONFIG:-file:$D2RQ_ROOT/etc/logback.xml}
exec java -cp "$CP" -Xmx1G "-Dlogback.configurationFile=${LOGCONFIG}" d2rq.generate_mapping "$@"
