#!/bin/bash
# $Id: generate-mapping,v 1.1 2006/05/30 07:29:00 cyganiak Exp $
D2RQ_ROOT=${0%/*}
SEP=':'
if [ "$(uname)" = "Cygwin" ]; then SEP=';'; fi
for jar in "$D2RQ_ROOT"/lib/*.jar "$D2RQ_ROOT"/lib/*/*.jar
do
  if [ "$CP" != "" ]; then CP="$CP$SEP"; fi
  CP="$CP$jar"
done
exec java -cp "$CP" d2rq.generate_mapping "$@"
