# q-langMatches-de-de.rq
# $Id: q-langMatches-de-de.rq,v 1.2 2009/02/09 12:21:31 fatorange Exp $

PREFIX : <http://www.purl.org/stuff/#>

SELECT *
{ 
	:rev ?p ?v . 
	FILTER langMatches(lang(?v), "de-de") . 
}
