PREFIX bsbm-inst: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>


SELECT * 
WHERE 
{

	<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/Product2> bsbm:productPropertyNumeric2 ?propertyNumeric2 .
	OPTIONAL 
	{ 
		<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/Product2> bsbm:productPropertyTextual4 ?propertyTextual4 
	}
	OPTIONAL
   	{ 
   		<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/Product2>  bsbm:productPropertyTextual5  ?propertyTextual5 .
   	} 	
}

