CREATE TABLE TABLE1 (ID INT PRIMARY KEY, REF INT);
INSERT INTO TABLE1 VALUES (1, 11);
INSERT INTO TABLE1 VALUES (2, 12);
INSERT INTO TABLE1 VALUES (3, NULL);
CREATE TABLE TABLE2 (ID INT PRIMARY KEY);
INSERT INTO TABLE2 VALUES (10);
INSERT INTO TABLE2 VALUES (11);
