PREFIX 	   :<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromVendor1/>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?v
{
    :Offer15 ?p ?o
    OPTIONAL 
    { 
    	?o bsbm:productPropertyNumeric1 ?v 
    }
}
