PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX  : <http://downlode.org/rdf/iso-3166/countries#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT  ?x
WHERE
{ 
    ?x bsbm:country :US .      
}
