PREFIX  xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX  : <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT  ?v1 ?v2
WHERE
{ 
	?x1 :rating1 ?v1 .
    ?x2 :rating1 ?v2 .  
    FILTER ( ?v1 != ?v2 ) .
}
