PREFIX 	   :<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromProducer1/> 
PREFIX bsbm:<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT ?value
{
	:Product2 bsbm:productPropertyNumeric1 ?value . 
	FILTER(?value = 1041) 
}
