PREFIX :<http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/dataFromRatingSite1/>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>

# DOT is part of the decimal.
SELECT * 
{ 
	:Review15 ?p -18 
}
